### ISSUE TITLE
客户端无法重连

### ISSUE THREAD

**Issue by NowFlying** [pjmike/springboot-netty#1]
服务端和客户端分开测试了你的代码，发现服务端在挂了以后客户端无法重连

**Comment by winkstu** [comment]
感觉没有成功注入 后面我用构造函数注入了就可以触发重连

**Comment by zhuhongbozhuhongbo** [comment]
作者本意是希望把nettyClient注入到HeartbeatHandler的nettyclient属性中。但HeartbeatHandler是在ClientHandlerInitilizer中通过new方法构造的实例，spring是不能向手动通过new方法创建的实例里面注入bean的。。。

**Comment by pjmike** [comment]
@zhuhongbozhuhongbo 感谢提醒，我没有把nettyclient注入成功，所以
导致客户端无法重连，后面我会重新push代码
